veg : mystring.cpp vegnews.cpp
	g++ -g mystring.cpp vegnews.cpp -o veg
say : mystring.cpp saying.cpp
	g++ -g mystring.cpp saying.cpp -o say
say2 : mystring.cpp saying2.cpp
	g++ -g mystring.cpp saying2.cpp -o say2	
