main : stacktem.cpp
	g++ -g stacktem.cpp -o main
main1: stkoptr1.cpp
	g++ -g stkoptr1.cpp -o main1
main2: tempmemb.cpp
	g++ -g tempmemb.cpp -o main2
main4: frnd2tmp.cpp
	g++ -g frnd2tmp.cpp -o main4
main5: tmp2tmp.cpp
	g++ -g tmp2tmp.cpp -o  main5
main6: manyfrnd.cpp
	g++ -g manyfrnd.cpp -o main6
